services:
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fasttravel
      MYSQL_USER: fasttravel
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}