services:
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: <Set using environment variables>
      MYSQL_DATABASE: fasttravel
      MYSQL_USER: fasttravel
#      MYSQL_PASSWORD: <Set using environment variables>